### ISSUE TITLE
Game refocus setting not working

### ISSUE THREAD

**Issue by maxeuronate77** [hawkeye-stan/msfs-popout-panel-manager#100]
Hi, 

I have enabled the game refocus setting, and enabled it in the profile and for each panel, but it is not working, and I still have to tap (click) out of the panels to re-enable the flight controls.

I'm using Spacedesk and an iPad. Popped out the GTC panels in the Vision Jet (G3000).

Let me know if you need further info.

Thanks much 
Max

**Comment by hawkeye-stan** [comment]
Hi Max,

Click the down arrow icon for the panel and make sure "Automatic Game Refocus" is enabled.  Also check in POPM preferences that Refocus Game Window is enabled. You can set it delay to 2 seconds since you're using Spacedesk to reduce the network latency and potential mouse emulation conflicts. If refocus is working, after touching GTC panel in spacedesk, the mouse cursor should return to center of MSFS game window.

Stan

![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/cb7d08d4-5646-4e5a-84ad-0ee55f07c194)

![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/4ea81b6c-4412-4fdd-9d57-31905d0c6cfa)

**Comment by maxeuronate77** [comment]
Cheers Stan - I think I just needed to restart POPM after making changes as it started to work straight after. On 5 Dec 2023, at 17:49, Stanley ***@***.***> wrote:﻿
Hi Max,
Click the down arrow icon for the panel and make sure "Automatic Game Refocus" is enabled.  Also check in POPM preferences that Refocus Game Window is enabled. You can set it delay to 2 seconds since you're using Spacedesk to reduce the network latency and potential mouse emulation conflicts. If refocus is working, after touching GTC panel in spacedesk, the mouse cursor should return to center of MSFS game window.
Stan
image.png (view on web)
image.png (view on web)

**Comment by hawkeye-stan** [comment]
Glad the issue is resolved.
