### ISSUE TITLE
Starting Pop out fails

### ISSUE THREAD

**Issue by hoverman59** [hawkeye-stan/msfs-popout-panel-manager#103]
Hi - while I'm a little new to msfs I am a also a pilot:) I am building a home cockpit with touch screens.
 I have been working with trying to get pop out manager to run for a while and following all of the tutorials.  I downloaded the Visual C ++ mentioned and  installed.

No matter what I do, which aircraft I try, I get the attached failure method when starting the pop out.  everything else to this point works fine.  I can pop out the screens with the right alt + left click and position them on my touch screens.  however, I cannot get the pop out manager to work so I can use the touch functions.

Windows 10 version 22h2 Nvidia 3080 graphics card

![msfs pop out fail](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/156255019/b777a515-c6ec-4d1e-add5-3e8494790dac)

Any  thoughts?

Thanks!

**Comment by hawkeye-stan** [comment]
Do you have the correct keyboard binding setup for "saving" and "loading" custom camera view in MSFS control setting. The binding needs to be Ctrl-Alt-0 and Alt-0 (the zero is the keyboard 0 and not the numpad 0). You can also change this in POPM preference setting to another number key.

Also test if you can pop out panel using Right-Alt Left-click manually since POPM relies on that.

**Comment by hoverman59** [comment]
Thanks for responding.  I found the error and posting this in case others have the same issue.  
I could pop out with the manual method but pop out manager was failing.   the fix:

I retraced my steps from when I first started this adventure.  There is an online video that shows you how to Pop Out - it was one of the first ones I watched, its about 4 minutes.  in it is says to go to your keyboard setting and search 'New UI'  you can assign a pop out key.  I had assigned the right CTRL key.  I went back and changed it the the right ALT key and it worked.
I still get an error  'Turning on TrackIR - FAILED' but the windows pop out.  not sure what the Track IR does..

Thanks for the help, It certainly was a strange one..glad we got it fixed...

**Comment by hawkeye-stan** [comment]
If you're not using TrackIR, you can remove the error by disabling Track IR in POPM preference setting

**Comment by KentLDahlgren** [comment]
Hi,

I have the same problem. That is that the log says Failed. Have tried the solutions named but still get the same error.

**Comment by georges2906** [comment]
Hello , I have downloaded the latest version of msfs-popout-panel-manager and after running the app and opening the flight simulator , nothing happens ! No pop out screen so I can start configuring profiles for my planes . I can see the app in the lower taskbar in windows 10 but cannot start nothing !
What did I do wrong ? I need very much this app . Thanks

**Comment by TBryson2** [comment]
Working with a friend, we had pop out manager working wonderfully.   Rebooted system, now all windows on main instrument panel FAIL to launch, window on "keee" panel will display properly.
Manger DOES detect correct aircraft.  When starting pop out windows, all we get is "failed", not sure why?  Tried new profile, no joy.  Where does POP manager keep the data files for remebering where the windows are located?  Since there isn't an install program, how do we totally remove ALL history of this program and start again?

Verified "New UI Window mode IS RIGHT ALT"  Nothing has changed.


UPDATE!  FIGURED IT OUT!  We zoomed in on the cockpit and the "targets" were no longer aligned on the MFD's.  Repositioned targets, and it works.
TB2
