### ISSUE TITLE
Program wont work at all

### ISSUE THREAD

**Issue by qbrayton823** [hawkeye-stan/msfs-popout-panel-manager#106]
Good day, I had MSFS Pop out manager working a few months ago, all of a sudden the interface just stopped working. Everytime I try to add a new acft or anything the program dims and freezes. Then I have to re open and the same this happens again and again. Please help

**Comment by hawkeye-stan** [comment]
Hi,

Sorry I don't have enough information to figure out why Pop Out Manager is freezing on your machine suddenly. Could there be new programs or Windows update installed on your machine that caused the freeze? A lot of different things could caused POPM to have conflict or crash. Since adding aircraft profile in Pop Out Manager does not involve connecting or checking for network connection, so network probably is not the issue. 

Please try re-download the latest version of POPM can see could it be file corruption.

**Comment by qbrayton823** [comment]
I download 3.46….and that seems to be the only version that works now. None of the new ones worksSent from my iPhoneOn Jan 26, 2024, at 08:15, Stanley ***@***.***> wrote:﻿
Hi,
Sorry I don't have enough information to figure out why Pop Out Manager is freezing on your machine suddenly. Could there be new programs or Windows update installed on your machine that caused the freeze? A lot of different things could caused POPM to have conflict or crash. Since adding aircraft profile in Pop Out Manager does not involve connecting or checking for network connection, so network probably is not the issue.
Please try re-download the latest version of POPM can see could it be file corruption.
