### ISSUE TITLE
MCDU in FBW A320 cannot be repositioned

### ISSUE THREAD

**Issue by keithholt** [hawkeye-stan/msfs-popout-panel-manager#107]
PFD and MFD work fine, but the MCDU pop out display is neither relocatable nor resizable.

**Comment by hawkeye-stan** [comment]
I'm not able to reproduce your issue. In the screenshot, I'm able to pop out the 3 panels and move them to the right size of my screen and resize them. Could it be something in your system that is blocking the MCDU pop out from being resized or moved or a corrupt FBW A320 installation?

<img width="1272" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/74772a0c-0773-47bf-ad6c-19eeb14044c0">

**Comment by hawkeye-stan** [comment]
I'm running the stable build of FBW A320, so developer build could be the issue. As for popping out to another monitor, there should not be a problem since I have mine setup the same way.  The screenshot I sent before was for illustration purpose. As for add-ons, I am also running Navigraph, so Navigraph definitely is not the issue. Maybe GSX conflicts with MCDU but I doubt it since I haven't receiving any report from Pop Out Manager users about not able to resize or relocate a pop out.

**Comment by keithholt** [comment]
Thanks for looking at this.  I guess there is not much I can do except wait and see if a future development build fixes something internal to FBW then.

I’ve been using Prepar3D v5.4 for simulation with my home cockpit, but every once in a while I try to see if MSFS is a viable replacement.  Every time I try I hit a brick wall with something or other in MSFS and go back to what works.  I imagine someday MSFS will be ready for serious use, but that day isn’t here yet.


Keith
