### ISSUE TITLE
"Always on Top" function not working all the time

### ISSUE THREAD

**Issue by karigon** [hawkeye-stan/msfs-popout-panel-manager#109]
I use this product together with air manager, with a solid black background instead of transparent (as I don't want to see my default window screen). Thus, I require the PFD/MFD/GTC popouts to always be on top of the air manager display.

Issue:
The feature works as after initial setting, the screens will always be on top of the air manager, even though I am touching the air manager features. However, air manager may end up on top of the screens when:
1) Starting a new flight
2) Doing 2nd leg of flight on the same flight, with engine switched off/on in between

For both cases, the "always on-top" feature need to be reset by manually toggling it off and turn on again.

**Comment by hawkeye-stan** [comment]
It is most likely a bug in MSFS or conflict with Air Manager. MSFS will try to redraw pop outs at certain point in a flight session that is out of control of POPM. This redraw of pop outs will overwrite "Always on Top" setting which was executed by POPM during the initial pop out. The other cause could be Air Manager is also sending Always on Top command for its panel which will overwrite POPM setting. Last to execute Always on Top command wins. 

The only way to workaround this issue is as you described, toggling Always on Top off then on, this will force POPM to reapply the setting.

I've noticed this issue before but unable to pinpoint exactly when MSFS redraws pop out. This bug (or game design) not only affects Always on Top setting but also Hide Title Bar setting. I'll look into it and see is there anything I can do about this issue.

**Comment by karigon** [comment]
Thank you for the clear explanation! I have not encountered issue with the hide title bar setting, it remains hidden even though the always on top has been reset. To clarify, my air manager's "always on top" is turned off and this only happened when I tried to interact with the air manager panels.
