### ISSUE TITLE
Taps not detected on touchscreen in Fenix A320

### ISSUE THREAD

**Issue by slemson** [hawkeye-stan/msfs-popout-panel-manager#111]
I'm not sure if this is user error or an actual issue. I've got a touchscreen monitor connected to my machine. In windows, it works. I can tap to click or double tap to double-click. I can select areas with my finger. In the sim, I have the Fenix iPad full-screened in that monitor. It can detect a swipe. I can move between panes on the home screen of Fenix and a few taps work in some screens. For example, when I'm on the map display, I can tap the tiny gear to change maps and I can tap the tiny triangle at the top center to open the module icons. But it doesn't detect taps on most of the UI. I see the circle appear where my finger taps but the iPad in game doesn't respond to the taps. I do have the screen enabled for touch in POPM. Am I doing something wrong or did I miss a readme about this?

**Comment by hawkeye-stan** [comment]
You may need to manually adjust the pop out using pop out window boarder to make the pop out full screen instead of double-clicking the pop out panel window title bar to make it full screen. There is a limitation when doing so does not send the correct window size/position to POPM for touch to mouse click emulation. You should then see POPM panel configuration for your pop out panel's width/height/top/left reflect the correct pop out size and location.

You can also use "Full screen mode" option in POPM panel configuration for the panel to make the pop out panel full screen. But his may change the aspect ratio of the panel since MSFS is controlling how the panel is being rendered.

**Comment by slemson** [comment]
Sorry for the delay. That did seem to fix things. I manually set the window to be slightly smaller than the resolution and now touch is working. Thank you!
