### ISSUE TITLE
Garmin GTN 750 only takes up 75% of the screen

### ISSUE THREAD

**Issue by ljkenny** [hawkeye-stan/msfs-popout-panel-manager#123]
The proportions are correct, but in this use-case that is not desirable.

Is there a way to stretch the panel to take up all of the external monitor - true full-screen?

**Comment by ljkenny** [comment]
![PXL_20240726_103806085 MP](https://github.com/user-attachments/assets/a88efbcf-0185-415a-aada-232efef84d8f)

**Comment by hawkeye-stan** [comment]
You can use full screen mode in POPM (which emulates 'Right-Alt + Enter' MSFS keystroke) or manually press the keystroke combination to switch the panel to full screen. But then the aspect ratio will most likely be wrong. I don't think there is anything you can do since the aspect ratio is defined by the panel developer and not easily modifiable unless you dive deep into the software code for the panel.

**Comment by ljkenny** [comment]
Incorrect aspect ratio at full-screen is preferable to correct aspect ratio at 75% screen.

I will give your instructions a try.  Thank you.

**Comment by ljkenny** [comment]
Unfortunately that didn't work.  Both the `Left-Alt + Enter` key-combination and the toggle in POPM give the screen you see above in the picture, complete with the big black bars across the top and bottom.  There doesn't seem to be a way to tell MSFS or POPM to stretch the panel to take-up that empty real estate.

**Comment by hawkeye-stan** [comment]
Looks like GTN 750 panel is already maximized on your tablet. I don't think there is a way to remove the top and bottom black bar.

**Comment by lag-google** [comment]
I see.  Thanks for your help.
