### ISSUE TITLE
No show little hand on panel

### ISSUE THREAD

**Issue by JefMore** [hawkeye-stan/msfs-popout-panel-manager#17]
Hello Mr Stan, in the video of how to use the application, it shows that when you put the pointer on the panel, the pointer changes to a little hand to select the panel. However, this does not happen in my case and despite the fact that I left click, the respective number does not appear. But if I move the pointer to the taskbar and left click then the number appears, but still I can't drag it to the panel I want to select. I would greatly appreciate any guidance or suggestion.

**Comment by hawkeye-stan** [comment]
The number circle panels actually are tiny application windows that sit on top (set to appear 'Always on Top') of all other opened application which includes MSFS. I am thinking something in your system is blocking the operation of these number circles panels. Can you try the following and see if MSFS is the culprit?

1. Just open Pop Out Panel Manager and nothing else (keep MSFS close) and create a test profile. Click "Start Panel Selection" and see if you can click anywhere on the desktop and see the number circles appear correctly at your mouse location. If so, then your mouse interaction with the application is working. If you cannot see and drag the number circles panel, see #4 below.

2. Run MSFS in "Window mode" instead of "Full screen" (configure in Display mode in MSFS configuration screen). Then repeat the above exercise and see if the number circles appear on top of the MSFS application window. If so, all is well.

3. Change MSFS display mode back to "Full Screen" and repeat the exercise. If you don't see the number circles, then somehow full screen mode is blocking my app.

4. For failure #1, #2 or #3 above, another culprit could be addon or windows utility you're running that prevent mouse cursor or application windows to operate correctly. Any utility that modifies windows position priority (such as setting windows always on top, etc) could interfere with Pop Out Manager.

I wish I can provide more help but unfortunately I'm not able to recrate your issue.

**Comment by JefMore** [comment]
Thanks for your prompt response Stan. After writing the question, I continued to try to solve the problem and run the application as administrator, and a window to update to v3.3.1.0 was displayed. after accepting, to my satisfaction, the program works perfectly. Thank you very much again for your contribution and interest.

**Comment by hawkeye-stan** [comment]
Nice! Glad the app is working for you.
