### ISSUE TITLE
Not working keep getting error messages

### ISSUE THREAD

**Issue by TheFuzzThatWas** [hawkeye-stan/msfs-popout-panel-manager#20]
[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/8929873/error.log)
I've tried numerous times with no luck,

**Comment by hawkeye-stan** [comment]
Cannot reproduce.

**Comment by TheFuzzThatWas** [comment]
I downloaded the new software and now I can use  one panel but get the same error on any further panels. I will try some more later but right I have just about given up on the software. Thanks for trying. Carl

**Comment by hawkeye-stan** [comment]
What kind of error are you getting? Is the app crashing or you have error message in the status area of the app showing you error?

**Comment by TheFuzzThatWas** [comment]
I get an error message, press ok and it crashes to desktop

**Comment by hawkeye-stan** [comment]
Will you be able to attach the error.log file here so I can investigate the issue regarding the new version of the app you just installed?  Thank you so much for your help and I hope I can figure out what is going on and get you up and running.

**Comment by TheFuzzThatWas** [comment]
Sent from Mail for Windows From: StanleySent: Sunday, June 26, 2022 3:48 PMTo: hawkeye-stan/msfs-popout-panel-managerCc: TheFuzzThatWas; AuthorSubject: Re: [hawkeye-stan/msfs-popout-panel-manager] Not working keep getting error messages (Issue #20) Will you be able to attach the error.log file here so I can investigate the issue regarding the new version of the app you just installed? Thank you so much for your help and I hope I can figure out what is going on and get you up and running.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by hawkeye-stan** [comment]
Hi TheFuzzThatWas,

Looks like the error.log file didn't come through. Would you be able to reattach the error.log file fromPop Out Manager installed folder?

**Comment by TheFuzzThatWas** [comment]
Sent from Mail for Windows From: StanleySent: Monday, June 27, 2022 11:47 AMTo: hawkeye-stan/msfs-popout-panel-managerCc: TheFuzzThatWas; AuthorSubject: Re: [hawkeye-stan/msfs-popout-panel-manager] Not working keep getting error messages (Issue #20) Hi TheFuzzThatWas,Looks like the error.log file didn't come through. Would you be able to reattach the error.log file fromPop Out Manager installed folder?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by hawkeye-stan** [comment]
Hi TheFuzzThatWas,

Somehow your reply still coming through to github as some CSS message header. Would you be able to drag and drop the error.log file into your comment similar to your first message in this thread from 11 days ago? Thanks.

**Comment by TheFuzzThatWas** [comment]
[](url
[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/9002852/error.log)
hope this works
)

**Comment by hawkeye-stan** [comment]
The error.log showed that you don't have read and possibly full write access to the folder and subfolders where you extracted MSFS Pop Out Manager. C:\Users\Carl Wilcox\Desktop\MSFS PopOut\Resources

The only way I can recreate your exact error on my system is to remove read access to "resources" folder inside pop out manager. Is there something in your system (for example: Antivirus or Windows permission setting) that prevents certain file access to your desktop folder?

You can try the following and see if it resolves your issue:

1. First, lets check you have the folder "resources" in pop out manager installed folder and you have access to it. Try to open folder "C:\Users\Carl Wilcox\Desktop\MSFS PopOut\Resources" on your desktop. If you can open it, you should see 6 png images in there. This means you have read access, skip to step 3.

2. If you do not have read access, try moving MSFS Pop Out Manager to a different location on your hard drive (for example: C:\MSFS PopOut) or re-extract the zip package to a different folder and run the program again. If it fails with the same error message you've before and you have anti-virus install, please disable it temporarily and see if it fixes your issue.

3. If you do have read access and you do not have antivirus, then I'm guessing some other program in your system is blocking access to certain file or folders. If you have anti-virus install, please disable it temporarily and see if it fixes your issue.

4. Also, there a little bit more to your error since your error.log also does not show detail debugging info compare to attached "debug test error.log" file when I was trying to recreate your exact problem. The error line numbers in your error.log file is missing compare to mine. This means your Windows account also have restriction in access to certain windows file type such as  "MSFSPopoutPanelManager.pdb" in pop out manager folder. The .pdb files are used to give my application more detail code information when problem occurs. I believe if we can figure out how to clear your Windows permission issue, pop out manager should work.

[debug test error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/9006246/debug.test.error.log)

Please report back if you can run pop out manager after trying the above steps.

**Comment by TheFuzzThatWas** [comment]
Wow, this is something. OK it didn’t work, but I reinstalled and setup 1 panel and it worked. Tried 2 panels and errors. So Id am going to quit when I’m ahead. I will live with 1 panel. Thank you so much for all your trouble.  Sent from Mail for Windows From: StanleySent: Tuesday, June 28, 2022 7:41 PMTo: hawkeye-stan/msfs-popout-panel-managerCc: TheFuzzThatWas; AuthorSubject: Re: [hawkeye-stan/msfs-popout-panel-manager] Not working keep getting error messages (Issue #20) The error.log showed that you don't have read and possibly full write access to the folder and subfolders where you extracted MSFS Pop Out Manager. C:\Users\Carl Wilcox\Desktop\MSFS PopOut\ResourcesThe only way I can recreate your exact error on my system is to remove read access to "resources" folder inside pop out manager. Is there something in your system (for example: Antivirus or Windows permission setting) that prevents certain file access to your desktop folder?You can try the following and see if it resolves your issue:First, lets check you have the folder "resources" in pop out manager installed folder and you have access to it. Try to open folder "C:\Users\Carl Wilcox\Desktop\MSFS PopOut\Resources" on your desktop. If you can open it, you should see 6 png images in there. This means you have read access, skip to step 3.If you do not have read access, try moving MSFS Pop Out Manager to a different location on your hard drive (for example: C:\MSFS PopOut) or re-extract the zip package to a different folder and run the program again. If it fails with the same error message you've before and you have anti-virus install, please disable it temporarily and see if it fixes your issue.If you do have read access and you do not have antivirus, then I'm guessing some other program in your system is blocking access to certain file or folders. If you have anti-virus install, please disable it temporarily and see if it fixes your issue.Also, there a little bit more to your error since your error.log also does not show detail debugging info compare to attached "debug test error.log" file when I was trying to recreate your exact problem. The error line numbers in your error.log file is missing compare to mine. This means your Windows account also have restriction in access to certain windows file type such as "MSFSPopoutPanelManager.pdb" in pop out manager folder. The .pdb files are used to give my application more detail code information when problem occurs. I believe if we can figure out how to clear your Windows permission issue, pop out manager should work.debug test error.logPlease report back if you can run pop out manager after trying the above steps.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
