### ISSUE TITLE
Auto panning does not always work

### ISSUE THREAD

**Issue by YLevesque34** [hawkeye-stan/msfs-popout-panel-manager#36]
Hi
MSFS pop-up panel manager works great except for an annoying issue.
I used it with FBW A32NX. Sometimes the auto panning works sometimes it is not working.
When the Pop out starts, I can see the auto panning trying to go to the wide view but quickly it reverts to the default view before the pop-out starts. 
Sometime it works fine and go to the wide view  and extract pop-out correctly.
I  disabled the auto panning and now I extract them manually by going to the wide view (alt-0) and pressing Start Pop-out button.
Do you have a solution ?
I saw previously that there is a Hotkey to start the pop-out but I forget it. Can you tell me what it is?

Thanks for your good work.

Yves Levesque

**Comment by hawkeye-stan** [comment]
Hi Yves,

Are you using current MSFS release version SU9 or the latest SU10 beta? 

A little background. How Pop Out Manager's auto panning works is it first executes a built-in keystroke of Ctrl-Space to center cockpit view before executing Alt-0 to overcome a MSFS design bug that Alt-0 does not always return you to custom camera view if your viewpoint is somewhere else before. You can trigger this issue by hold down right mouse button and move to a different view, and then press Alt-0. Sometime it does not return you to your predefined custom camera.

Since SU9, MSFS key binding became glitchy to set the custom camera view. SU10 beta release 1 seemed to fix it and it became glitchy again in the last 2 beta releases. That is what you're seeing when the screen tries to pan and it glitches back.

I've found that setting keyboard control bindings a certain way for above 2 keystrokes help alleviate the glitch. The issue is keystrokes will get mess up if there are multiple bindings to the same game function or if your main key assignment is on the 2nd column in the binding.

In screenshot 1, search for the keystroke Ctrl-space in keyboard setting and make sure there is nothing in the 2nd binding column. I believed I had "F" bound to the 2nd column and I removed it.

In screenshot 2, search for the keystroke Alt-0 and make sure there is nothing in the 2nd binding column also.

![ss1](https://user-images.githubusercontent.com/72271266/184054215-da1312f4-a590-45a4-9c4f-4a5b28488817.png)
![ss2](https://user-images.githubusercontent.com/72271266/184054237-0673ea6c-fb79-4047-aa74-dde5607c913e.png)

Since I've also experienced this problem myself, I'm already in the process of implementing different ways to send keystrokes to overcome this issue and my latest code seems to work better. I'll be releasing this change in next release of Pop Out Manager probably this coming weekend or early next week and hopefully it will permanently fix your issue. I'm also going to keep up with this issue and wait for SU10 official release later this month to see if I have to make further adjustment.

Please let me know if the above fix works for you.

Best regards,
Stanley

**Comment by YLevesque34** [comment]
Hi Stanley.
Thanks for your response.
I use SU9. I had 2 keystrokes bindings for these 2 commands. I removed the
second assignment and it seems better now.
I will test your version 3.4.2 and let you know.

Yves

**Comment by hawkeye-stan** [comment]
Updated code to extend auto panning timing in v3.4.2. Hopefully with this code change and using in conjunction with the above control setting fix, it will overcome current MSFS bug (as of SU10 Beta 1.27.16.0) that loading custom camera does not work consistently on command.
