### ISSUE TITLE
Screens Not Popping out on PMDG 737-700 (ALSO NEED an UNDO Feature.

### ISSUE THREAD

**Issue by menardrs1** [hawkeye-stan/msfs-popout-panel-manager#39]
I can select each of 5 screens and the numbered Circle appears but when I "Start Pop Out" it only selects the Pilots main Navigation Display
![PMDG 737-700](https://user-images.githubusercontent.com/112193159/186949200-49fe22c1-b48b-42e8-9dcf-9cbab68fc86d.png)

The results are here. I have triple 55" 4 K screens, 3 RSG Displays and a 27" Utility Screen run on 2 GPUs. I've spent two hours trying to get this app to work with no success. 

* - Need an UNDO button if you pick the wrong display
* - Need a Clear one or all Panels Button. Each time the process fails I have to delete the Profile and start over.
![PMDG 737-700 -1](https://user-images.githubusercontent.com/112193159/186950109-1c0aa2bf-b7e6-48ac-a1e1-e42b5f279da9.png)

**Comment by hawkeye-stan** [comment]
Hi menardrs1,

Looks like Pop Up Manager is unable to pop out the first panel. Looking at your screenshots, like Pop Out Manager failed to pop out panel for unknown reason. Please try running Pop Out Panel Manager as administrator. Couple of users had reported that panels won't pop out unless running the app as admin. I'm still investigating this issue. Unfortunately, I'm not able to produce this issue on my machine. Issue https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/33

As for undo feature, as you're selecting panel, you can do SHIFT-Left click to undo panel selection. 

To clear all panel data, you can click on "Start Panel Selection" button again for your selected profile. Pop Out Manager will warn you if you want to overwrite all panels' configuration and this also includes clearing all pop out final locations data.

Stanley

**Comment by menardrs1** [comment]
I am running as Administrator. That is what I don’t understand. It is most likely that fact I am running two GPUs and 7 displays. Can you recreate that scenario? If not we may never figure this out.

Thanks for the effort.

Sent from my iPhone

Scott Menard

**Comment by hawkeye-stan** [comment]
Hi Menard,

Unfortunately, after spending few hours yesterday night to recreate your issue, I was unable to do so on my Windows 11 machine and a Windows 10 machine. Since Pop Out Manager uses low level keyboard code to send pop out keystroke commands to MSFS, maybe something unique to your machine (a program or windows update) is blocking the signals. When other users reported this particular issue of not able to pop out panel, run as administrator would resolved their issue and I haven't received any report about not able to do so yet. Also, I think multiple GPUs and 7 displays should not be the cause since I have users who have similar cockpit setup. This is really a head scratcher!

No matter what, I will continue to try to identify and reproduce your issue. My believe is that the only explanation is either something in my code, which I haven't been able to identify yet, Windows setup, or the game itself, that is causing your unique issue. Hopefully I will be able to figure this out.

Stanley

**Comment by menardrs1** [comment]
Sorry to cause you such grief. I am able to manually pop the windows by holding the ALT + CLICK. All the selected windows are combined into a dbx. From there I again hold the right ALT key and left click to extract a window from the group then drag and resize and position onto the display of choice. Repeat the process for all remaining panels and displays. Will attempt again today creating a number of profiles for the PMDG 737-700 by adding 1 panel then 2, 3, 4, and then hopefully the last with all 5 panels. I’ll post any further anomalies if they they occur. Not had any issues with my keyboard, which is plugged directly into a native USB port of the PC and not via a hub.

If you can think of anything else I might try please let me know. Thanks 


Scott Menard

**Comment by kPanesar** [comment]
Maybe try creating a custom view with the panels visible using the `Ctrl + Alt + number key` shortcut, then tell the panel manager to use that shortcut in the preferences, and see if it can popout the panels using that custom view. I've had to create a custom view and try clicking on different locations on the displays to get the application to work properly for some aircraft (the location clicked by the applications seems to be slightly different from the one clicked during panel selection). When it's popping the panels out, you'll see where the mouse cursor is being clicked to know if it's clicking the right spot or if it's off of the display.

**Comment by menardrs1** [comment]
No Joy! I tried creating a Single Popout and even that failed with the same error
Create Profile:
![image](https://user-images.githubusercontent.com/112193159/187076554-2cf9c997-ac0d-42df-bc05-b3401eef8c60.png)

Go to Custom View:
![image](https://user-images.githubusercontent.com/112193159/187076596-4bff5d7d-3392-4ca5-b909-b98f91b4ecb1.png)

Start Panel Selection (Press button)
Note: Main screen moves to background but I Alt/Tab to return it so it will appear in image)
![image](https://user-images.githubusercontent.com/112193159/187076821-32938b5f-1e79-4ed7-b28d-261b6e67b75c.png)


Start Pop Out"
![image](https://user-images.githubusercontent.com/112193159/187076876-605e9d48-aeca-4799-be13-080fab956ed7.png)

I'm at a loss!!!!!

Below is the goal.
![Menard PopOut Mgr Goal](https://user-images.githubusercontent.com/112193159/187077162-f31ab5b1-19eb-4bbf-8dbd-bf4315d97743.jpg)

**Comment by hawkeye-stan** [comment]
Hi Menard,

Panel coordinate looks good and auto panning seems to work in your screenshots. Something on your system is blocking Pop Out Manager's click command. The error message is basically saying it cannot verify pop out panel is on the screen after Pop Out Manager sends a "fire and forget" command to MSFS to pop out the panel.

One last thing to check is once you've completed the panel selection in your profile. Check the checkbox "Edit Panel Location Overlay" in the lower right corner in Pop Out Manager main screen. What this does is it displays your number circle alignment with panel and the custom camera angle used during panel selection. If everything lines up, then the failure in Pop Out Panel sending Right-Alt click command is most likely the culprit. If panel does not line up, then loading and saving of auto panning custom camera angle did not work. You can then check if in game key binding matches what is specified in Pop Out Manager preferences. (Ctrl-Alt-Number / Alt-Number)

![Screenshot 2022-08-28 104806](https://user-images.githubusercontent.com/72271266/187080065-c2e1dc47-213a-4673-9c1b-736bd4091a1d.png)

Are you on SU10 beta? If so, there is an new option to add addition pop out key binding in the game instead of just Right-Alt Left click and it may help. Also, if you're in full screen mode for the game, see if running in Windows mode allow Pop Out Manager's click command to go through.

![Screenshot 2022-08-28 101627](https://user-images.githubusercontent.com/72271266/187078581-4d950559-9552-4a4f-8b9e-0f5a43b8a29b.png)

![Screenshot 2022-08-28 101740](https://user-images.githubusercontent.com/72271266/187078615-26891856-e39b-49b8-9bd0-2110328e82a6.png)

Unfortunately, you're the first user who is running into this issue where run as administrator does not fix it and I'm really sorry I'm not able figure out what is causing your issue so far.

Stanley

**Comment by menardrs1** [comment]
I have a pretty unique setup so this does not surprise me.  No, I am not on SU10 beta,  and I did tick the Edit Panel Location Overlay and still no panels.
I am not sure I understand your instructions which is why I asked for a video. Perhaps one of your users is a content creator and would make one. Also, I may not fully understand the Camera View issue so I have posted a pic of how my Keyboard bindings around the Custom Save and Load group. If you know of a way to print them all out I would be happy to send them to you  (these are default afaik). I can also tell you how I go about picking Panels manually - I have to Hold the Right ALT Key + Left Click the mouse. Now, sometimes I have to click it twice to get the panel to pop out into the group formed on a different screen (not the main MSFS display). I am suspect the fact multiple mouse clicks are sometimes needed is the culprit. Below are my Keyboard bindings. If this is not correct, please advise how to fix. Thanks
![image](https://user-images.githubusercontent.com/112193159/187175282-5e2286e7-a44d-48c6-b684-2235e8282b30.png)

**Comment by menardrs1** [comment]
Making some progress... See image below. Panel pops out just fine but the app is saying  "unable to pop out panel number 2. I moved the group from another screen so I could capture everything in one shot.  I set the Return View (ALT + 9) which is my Pilot View. What is shown in the first image below is what your app is doing. 
![image](https://user-images.githubusercontent.com/112193159/187183837-eaf18c64-4361-4b46-92da-9b61345546f3.png)

**Comment by menardrs1** [comment]
I got it! It was the Custom Views that was screwing things up. The image below is a Snipit of all the panels in position. The FMC and PFD are fine but notice the Three panels on one Display with the Title Bar. I am placing three panels on my 15" G1000 MFD (RSG) and would like the remove the Title Bar but it does not work in your app.

![Complete 5 Panel PopOut](https://user-images.githubusercontent.com/112193159/187188906-fc3a7e2c-b571-4b7f-8df2-86fa64e73512.jpg)

**Comment by hawkeye-stan** [comment]
Hi Menard,

Got a little time before my work day starts to test out your issue. I'm so glad you're almost there to get everything working. You may have actually stumble onto multiple MSFS bugs from time to time as below and we've to wait for Asobo to provide fixes for them..

1. Why panels are zooming in and out? 

This is to make sure custom camera view loaded correctly on first key press. To overcome this MSFS bug, Pop Out Manager has to do send a "reset cockpit view" key command before sending your defined "load custom view" command for auto panning. On top of that, there is a bug in "reset cockpit view command" since SU9 and here is the fix I discovered to fix it if you encounter this issue.

GitHub Issue https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/36

2. Unable to hide title bar for panels?

Please see my screenshot below of trying to recreate your setup (I just put all panels onto the same screen for screenshot purpose). You may have encounter another MSFS bug where moving panel while title bar is hidden will mess up the hide title bar function in Windows. To overcome this, just move all panels into positions and check all required "hide title bar" checkboxes and lock the profile. The title bar for these panels may not be hidden initially. Then, just select "restart" from the Pop Out Manager's file menu and "Start Pop Out" again and this will reset MSFS broken hide title bar function.

If you're unable to hide title bar at all even after reset, then this is something new and I will need to investigate what is causing it.

![Screenshot 2022-08-29 101112](https://user-images.githubusercontent.com/72271266/187222341-1ec9e1a1-533b-404d-9133-8c479886f6a5.png)

Stanley

**Comment by menardrs1** [comment]
That did it! All Titles are hidden and in the correct position. Thanks for being so patient with me.

**Comment by hawkeye-stan** [comment]
You're very welcome :)

**Comment by menardrs1** [comment]
Well, Starting up today using the same profile that worked yesterday, I am getting the same error "Un able to pop out the First panel". When I check the "Panel Location Overlay" box and the "Start Pop Out" button, I don not get the Number Circles to show me where the alignment is located. Now what?

**Comment by hawkeye-stan** [comment]
Hmm... I'm at a lost of why your configuration does not work today.

One thing I can think of is the Number Circles are missing can be explained that they did appear on one of your monitor or could be totally off screen to some invalid coordinates because your Windows display configuration has somehow been changed when you boot up your PC. Pop Out Manager relies on your Windows display configuration to set and not change so panel coordinate alignments are constant. This will also explain why Pop Out Manager cannot pop out the first panel because it tries to click in no man's land. Unfortunately, I won't be able to debug your issue without access to you PC and see what your Windows display settings, display resolution, and display scale are set as and how they interact with Pop Out Manager's panel coordinates system. And to see are there anything in your system that could be interfering with Pop Out Manager's operation.

One other thing to check is if you run the game in Windowed Mode, your MSFS game window has to be at similar position as when you select your panels. A new feature will be added in next version of Pop Out Manager to automatically save and load MSFS game window position. GitHub issue https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/38

One thing to test the theory that booting up PC could be messing with Pop Out Manager is to try this:

1. In Pop Out Manager, create a new "test" profile, bind it to your 737 aircraft, and select couple panels (you can pan the cockpit view to some off angle to even make sure Auto Panning works).
2. Start pop out panel, then configure panel final display positions and lock the profile.
3. Restart your flight in the game and panels should automatically pop out because of aircraft binding.
4. Now quit MSFS, and restart your PC.
5. After PC has been restarted, start MSFS and Pop Out Manager
6. Start a flight with 737 and the panels you selected earlier should automatically pop out

If any of the about steps fail, especially after restarting your PC, then something in your system is most likely interfering with Windows display setting and Pop Out Manager.
