### ISSUE TITLE
Pop Out Manager Touch Does Not Work on NX Cub

### ISSUE THREAD

**Issue by rockywaves** [hawkeye-stan/msfs-popout-panel-manager#41]
The GX3 pop out with Touch enabled does not function as expected using the Air Manager GX3 Instrument.  The GX3 Instrument is a GitHub Sim Instrumentation download.  Touch is enabled on the Pop Out Manager, and Air Manager is set to transparent, but neither the mouse or touch work with the instrument.

**Comment by hawkeye-stan** [comment]
Hi rockywaves,

If I understood correctly, you said mouse control also does not work on this particular pop out panel. Then Pop Out Panel Manager touch support will not work either since it only translates touch screen input into mouse input.

Stanley

**Comment by rockywaves** [comment]
Hey Hawkeye-Stan,
Let me see if I can provide a better explanation.  I have the pop-out
manager working with the Air Manager - Garmin 1000NXi instrument overlay
without any issues in a Cessna 172.

In the MSFS, I want to the fly the MSFSCub Crafter which has a Garmin GX3.
The pop-out allows me select and pop-out the GX3 screen.  The GX3 is a
touch screen in the real plane.  In the sim it works with mouse and touch
inputs. I can get the pop-out to work on a touch screen, but only if I
don’t place it behind the Air Manager GX3 instrument panel.  Touch and
mouse inputs work on the instrument panel overlay, but not on the GX3
pop-out when they are integrated together.

My guess is it has nothing to do with the pop-out manager, but something to
do with Air Manager instrument panel.  I am very new user with both Air
Manager and the MSFS Pop-out manager, so not much experience on how
troubleshoot this issue.

I plan as my next troubleshooting step to overlay the GX3 pop-out with
Garmin 1000NXi Air Manager instrument overlay and see the mouse and touch
inputs work.

I appreciate any advice that you can give me.

**Comment by hawkeye-stan** [comment]
Hi rockywaves,

Yeah, give it a test if Air Manager G1000NXi community panel by simstrumentation works. The thing to test is the hollow frame inside the bezel allow touch passthrough into pop out screen. I believe G1000NXi definitely should work because many Pop Out Manager users are using it with touch support. If it does not work for you, then something in your Air Manager setup is not allowing mouse passthrough into the pop out. You can contact [Crunchmeister71](https://forums.flightsimulator.com/u/Crunchmeister71) in Flightsimulator.com forum. He is the creator of G1000Nxi panel and he will be able to help. If G1000Nxi works with the GX3 pop out window, then your Air Manager GX3 instrument panel overlay is not working. Just make sure the panel overlay allow passthrough into the pop out behind it.

I'm sorry I'm not able to help you more to test your scenario since I personally do not use Air Manager and I am not 100% sure about where the Air Manager settings are.  One thing I know is the mouse passthrough setting is definitely there and you've to configure the panel overlay to explicitly allow mouse passthrough. Maybe the G3X instrumentation panel you're using did not have this particular setting turn on by default.

Please report back if it is the G3X panel overlay issue or pop out issue. In the mean time, I'll try to find out more info and also see if other users are experiencing the same problem as you're when using G3X panel overlay.

Stanley

**Comment by rockywaves** [comment]
I found the problem in Air Manager.  The first step in Air Manager is to
create a new Panel.  The second step is to install the GX3 instrument in
the new panel.  The third step is to return to the new Panel and see if
"Click-thru" is checked.  In my case, it was not, so I deleted the panel
and created a new panel, and checked "Pass-thru" before proceeding to the
next two steps for installation of the GX3 instrument bezel.  Touch input
now work on my touch monitor, but with one other little annoyance.  When I
touch a know and spin it, the internal cockpit camera in the sim begins to
pan-around.  I have two monitors:  The touch monitor and a non-touch
monitor where I display the sim.  The touch-monitor display is extended
from the non-touch display.  I may have the multi-monitor setup wrong. My
Knobster is arriving today, so I plan to installed it, and see it I get the
same behavior with it.

Thanks you for your time, Hawkeye-Stan,

Rockywaves

Bob

**Comment by hawkeye-stan** [comment]
HI Bob,

I've contacted SimInnovations regarding your issue about using the built-in UI spinner to turn a knob. They replied it is a known bug in MSFS and Microsoft/Asobo will need to fix it in future software update, hopefully in the upcoming SU10. But since you've a knobster on the way, hopefully it should work around the issue since knobster will do all the knob turning.

Stanley

**Comment by rockywaves** [comment]
Thank you Stanley,

Good to know it is a bug and on their radar.  I have my Knobster working
and it works great.   The touch input bug does not effect the behavior of
the Knobster.

As always, grateful for your help,

Bob

**Comment by hawkeye-stan** [comment]
Hi Bob, so glad that your Air Manager and knobster is working! Happy flying!
