### ISSUE TITLE
2nd Panel Fails to Pop Out

### ISSUE THREAD

**Issue by PaulFMcG** [hawkeye-stan/msfs-popout-panel-manager#44]
I am using the C172 with G1000 and the 2nd panel is saying it cant be popped out even though i see it popped out next to the 1st one.
It was working before, but for some reason it no longer works.
I have version 3.4.5 and even tried to reinstall as well as redo the settings.
I have panning off and can verify the 1 & 2 are placed with no obstructions and as mentioned...i see the 2nd panel popped out next to the 1st.
Any chance it needs to pop out seperately as i see it doing it in the same window as the 1st?

![image](https://user-images.githubusercontent.com/111211008/200208374-568ea6d9-118d-4777-854b-44b17c52613b.png)

Thank You for your help on this

**Comment by hawkeye-stan** [comment]
Hi PaulFMcG,

Sorry didn't reply to your issue earlier (came down with the flu all week). I just did a test with Cessna 172 G1000 on multiple screen resolution (1080p, 1440p, and 4K) and was unable to reproduce your issue. It does look like it is a panel separation issue as you've stated. You don't have to pop out the panels separately. If you just start having this problem with v3.4.5, something unexpected is going on since my app did not have any code changes to the panel separation process. In any case, I'll look deeper into it and see if anything in my app's code that might have caused your issue.

In the meantime, please see if you can reinstall previous version of the app (v3.4.4.1011) from my github repository. Just download the zip file, extract it and replace the exe. You can also clear the below temporary Windows folder where Pop Out Manager uses when it is run for a clean install. I'll follow up on your github issue you created as I find out more.

"%userprofile%\AppData\Local\Temp\.net\MSFSPopoutPanelManager"

https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/tag/v3.4.4.1011

Stanley

**Comment by hawkeye-stan** [comment]
Copied from reply on Flightsimulator.com and thank you PaulFMcG:

-------------------------------------------------------------

Hey there…i have an update that might help others…
The issue regarding the 2nd panel not popping out correctly has been Solved.

Turns out this was happening due to Nvidia Geforce Experience filters being turned on. (ALT+F3)

I tested by turning it on and off… and each time it was on, the 2nd panel error message would appear.

Hope this helps others…
