### ISSUE TITLE
Popout Manager freezing sim

### ISSUE THREAD

**Issue by CaptainMcduff** [hawkeye-stan/msfs-popout-panel-manager#51]
Hi guys, this software was working flawlessly until last week. Now when the panels pop out, the sim freezes and I have to shut it down through task manager. The popout manager works well with the PFD/ND on both the captains and F.O side but when I attempt to resize the upper and lower EICAS, the sim freezes. Could it be down to the screen resolutions? I am using the PMDG 737-800.
Many thanks
Andrew

**Comment by hawkeye-stan** [comment]
Sorry for the late reply. I'm not able reproduce your issue as I also fly PMDG 737-800 mostly. It could be something with MSFS installs/community plugins that could be freezing the sim. Since EICAS is just another pop out window, it should work the same as  PFD/ND. If I encounter this on my end, I'll surely report back and will investigate the issue.

**Comment by CaptainMcduff** [comment]
Hi there, I've managed to solve the issue by accident. From what I had been doing, it seems the sim needs to be loaded up and ready at the gate before starting the pop out manager. I think I was overly keen to get all my software loaded before the start of the flight.
Many thanks for getting back to me.

**Comment by AaIiGee** [comment]
Hi, I have a same kind of problem as the sim freezes after I start panel pop out. It opens up a window to the left upper corner of the monitor but after that happens anything. The result is the same with Airbus H145 and Cessna 414AW.  In my case it dosen't matter if I start Pop Out Manager after the sim has loaded. Pop Out Manager worked just fine couple of weeks before that suddenly occured. I have tried to create new profiles but the same happens. No idea how to continue and some help would be great, thank you!

[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/10332184/error.log)

**Comment by hawkeye-stan** [comment]
The error.log looks OK, your MSFS freezing could be from something else new since POPM hasn't been updated and your issue just start happening. One check is if you have any community plugins installed, would you be able to disable all of them including your custom aircrafts and run MSFS (use MSFS Addon Linker can simplify this process)? After that, start MSFS, pick a default aircraft, run POPM and pop out some panels and see if you're getting freezes. If so, then something in your system, could be Windows updates or configuration changes is causing the freeze since both POPM and SU11 were released more than a month ago. Or there is an undiscover conflict with POPM that could be causing your issue and I can investigate on my end to try to recreate it. MSFS installation could be corrupted but very very unlikely. If everything runs fine, then most likely a community plugin is causing the freeze.

**Comment by AaIiGee** [comment]
Thank you for the reply, unfortunately cleaning the Community folder and loading a default aircraft didn't work. If it comes from my system I'm in real trouble. This is because I have only one month old system and I have been doing configuration changes all the time. I can remember that the freezing started at the same time I started to use TrackIR, but hard to imagine any connection to it especiaslly as the result is the same when TrackIR is turned off. But I'll follow this topic if you will get some idea what could be a reason!

**Comment by AaIiGee** [comment]
One thing I noticed is that the freezing happens also when I press the middle button of the attached image. The window moves to the upper left coner of the monitor just like with POPM and the freezing starts
![Näyttökuva 2023-01-05 200039](https://user-images.githubusercontent.com/121811286/210849671-6a72aaac-6f44-42e0-85da-099171ab7a47.png)
. So this not a POPM problem but is it a Windows or MSFS problem?
