### ISSUE TITLE
BSOD with Pop Out Manager and Device Interface Manager

### ISSUE THREAD

**Issue by DFWFlyDC9** [hawkeye-stan/msfs-popout-panel-manager#52]
Good morning,
I am running a FlightDeck Solutions Airbus MCDU with POM and Device Interface Manager. 
Running into an issue using when pop out manager is initially auto popping out windows while device interface manager is running I get a BSOD. I start DIM and POP via the exe.xml for ease of startup and although I could start the DIM manually after the sim is up and running I wanted to see if you could take a look at the log file and potentially have a solution. Thank you!

[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/10332697/error.log)

**Comment by hawkeye-stan** [comment]
The error log looks OK. The last error in the log "SimConnect receive message exception" will happen from time to time because of how MSFS SimConnect behaves. Since you got a BSOD, so the critical error has to be somewhere else since POPM won't be able to log anything at all when it happens. Usually BSOD is caused by system memory issue, driver issue or less frequently application conflicts. Since both your FlightDeck Solutions and POPM did not get update recently, some other updates in your Windows must have introduced the conflict. It could be an DLL updates by Windows or other program that is causing your BSOD. Also, if you've updated your FlightDeck MCDU app and it uses a different SimConnect DLL, it "may" cause system crash but I believe it is unlikely. 

One thing to try is since you have both MCDU and POPM running and BSOD, can you try run just one of them only at a time and see if you get BSOD. If it does not, then somehow when running them together is triggering a crash.
