### ISSUE TITLE
Main window focus does not work

### ISSUE THREAD

**Issue by JMMAZ** [hawkeye-stan/msfs-popout-panel-manager#56]
Stanley,  I have installed and used PPM for a while.  A great program.  I am using an LG 48 (main), and two 15.6 IP's for the popouts.  AM and Knobster are current and work fine.  I have followed the instructions to a "T", but still lose focus on the main screen after using touch on #2 or #3.  I have "touch enabled", but still losing focus...........  any ideas would be greatly appreciated.

James M (JMMAZ)

**Comment by hawkeye-stan** [comment]
Hi James, do you have "Refocus Game Window" enable in POPM. You can find this setting in File => Preferences => Touch Settings?

**Comment by JMMAZ** [comment]
Yes, it is enabled in Preferences and the panel setup screen

**Comment by hawkeye-stan** [comment]
When you say lose focus on the main screen (MSFS game window), do you mean you lose focus on flight control (your joysticks/game pad)?  This is a known bug in MSFS that when you interact with any pop out, either using your mouse clicking on it or hover on it, or touching the pop out on your touch monitor, you will lose flight control. Since your pop outs are managed by POPM and when touch is detected, after set amount of time (1 sec), POPM will try to click the main game window behind the scene to re-enable your flight control. 

It looks like POPM is not detecting you have touched the pop out so focus is unable to send to the MSFS main game window. Is your Air Manager bezel set to always on top of the pop outs and you have activated click-through set in Air Manager? Air Manager needs to pass click event to the pop out underneath so POPM can detect it.

![image](https://user-images.githubusercontent.com/72271266/212358815-814919ff-4baa-4e9b-8672-5b9c08cb3e10.png)

**Comment by JMMAZ** [comment]
Stanley,
Everything you suggested has already been done and rechecked.  When using AM and PPM, if I touch a control (hdg, alt, etc) the control knob turns kind of yellow and then either with my finger or Knobster, I can change the settings.  About 1-1.5 seconds later, the yellow on the knob fades to about 20% of its original brightness and stays that color.  In order to respond to ATC, or whatever on the main screen, I have to move to the main screen and click it with the mouse.  I understand that this is a long going problem with MSFS.  I was just hoping by what I have read that PPM could/would solve this.

**Comment by hawkeye-stan** [comment]
Hi James,

I think I misunderstood what you described before since you said when you touch a control knob, you can turn it with you finger or knobster. That tells me you're touching the Air Manager bezel and not a touch-enabled pop out panel (such as G3000 or GTN750). But the thing is touching Air Manager's bezel should not make MSFS to lose focus. Could it be the pop out that you placed inside Air Manager's bezel was overlapping and inadvertently gained focus? POPM cannot detecting any interaction with Air Manager's panel bezel. 

Try disabling the "Click-through" setting to make sure Air Manager is not passing mouse focus to any pop out panel underneath. In any case, I'm at a lost of what could your MSFS game window to lose focus when you're not touching the pop out panels themselves.

Btw, what aircraft are you flying and what pop out panels are you using in addition to the  Air Manager bezel you are using? I can try recreate your issue if I own the aircraft you're flying with.

Stanley
