### ISSUE TITLE
About 1 in 4 flights will swap two panels

### ISSUE THREAD

**Issue by brianavid** [hawkeye-stan/msfs-popout-panel-manager#59]
Generally this has worked very well for me and makes starting a flight very smooth.

But recently I have started to use a second screen (both using SpaceDesk) for a G1000 PFD and MFD. And about one flight in three or four, the popouts are placed on the wrong screen. Both are correctly sized and placed within an AM G1000 bezel - just the wrong way round. If I just restart the flight, very likely all will work fine - there is no need to restart SpaceDesk or AM.

Could there be a subtle timing error that lets the two popouts be mis-identified?

**Comment by hawkeye-stan** [comment]
It should not be because POPM pop out is based on sequence of pop out and not by panel identification. So, if you setup your profile to pop out PFD first then MFD second and place them in the previously saved locations, their pop out sequence and placements should always be the same. Anything else such as POPM only pop out 3 out of the 4 panels because of timing issue or out of sequence, it will result in error and not with panels being swapped.

I haven't used G1000 much and it could be G1000 is popping out the wrong panel when POPM clicks on them or you manually click on them. I'll keep this issue in mind and see if I'm able to reproduce it.

**Comment by brianavid** [comment]
Thanks for the reply. My intention was mainly to draw it to your attention.
In practice, it is not a big deal as it can only happen at the start of a
flight. If it is wrong I just restart the flight straight away and it will
usually be right. It could be a G1000 NXi problem I guess. But that's the
only panel I have used so far.
