### ISSUE TITLE
New request

### ISSUE THREAD

**Issue by i-dany** [hawkeye-stan/msfs-popout-panel-manager#6]
Thanks for the helpful program. I have a request: if I use the soft well, currently changing the screen, for example from the main view of the cockpit to overhead, I take the popup instruments with me. Obviously in the new screen I am forced to close them because they are bulky. Returning to the cockpit view, to reopen the pop up instruments I have to relaunch the program. Would there be a quicker and more direct way to get the instruments back in place correctly in the main view cockpit ? ( my basic situation… ) Thank you.

**Comment by hawkeye-stan** [comment]
Hi i-dany,

If I understanding correctly, you would like to have a way to reapply your "saved" panel settings when you move from view to view without redoing the pop out process? Your described scenario is:

1.  Initially pop out panels in the cockpit view, the panels are now at their desired location on your main monitor. 
2.  You then change the view to look at and operate the overhead instruments on the plane. To not block your main monitor's view when operating overhead instruments, you close the pop outs.
3. When you change back to the main cockpit view, you now have to re-pop out the panels in order to reapply their saved locations again.

Please let me know if I understand your scenario correctly?

From the above scenario, I think I can create either a temporary hide panels function or something along the line of reapply last saved locations function to the app. This way, when you want to move to another view to do things, you can temporarily hide or move the pop out panels out of the way. When you move back to the main cockpit view, you can then click a button and the panels with appear back at their assigned locations.

**Comment by i-dany** [comment]
Thank you for your attention to my request. You have perfectly understood my need and I am waiting for a possible solution. Thanks again.

**Comment by hawkeye-stan** [comment]
Awesome, I'll start investigating it and will try to code your requested feature into next update of the app.

**Comment by i-dany** [comment]
Very good. Thanks!Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Stanley ***@***.***> Data: 16/01/22  17:13  (GMT+01:00) A: hawkeye-stan/msfs-popout-panel-manager ***@***.***> Cc: i-dany ***@***.***>, Author ***@***.***> Oggetto: Re: [hawkeye-stan/msfs-popout-panel-manager] New request (Issue #6) 
Awesome, I'll start investigating it and will try to code your requested feature into next update of the app.

**Comment by hawkeye-stan** [comment]
Hi i-dany,

Requested feature has been added in the latest release 3.1. There is now a "Minimize all panels" function in the menu bar. You can toggle it to minimize all panels temporarily when you want to view your screen content.

Stanley
