### ISSUE TITLE
MSFS Popout Panel Manager Doesn't Work With SU12

### ISSUE THREAD

**Issue by skypilotYTS** [hawkeye-stan/msfs-popout-panel-manager#64]
Good evening,

MSFS SU12 just launched and with it, they have implemented a feature to remember where the screens have been placed after pop out and their size.

"Glass cockpit externalization has been reworked. There’s no intermediate window anymore; each glass cockpit opens a distinct window with the glass cockpit name. [Window position and size is saved when ending a flight. 9](https://forums.flightsimulator.com/t/popped-out-panels-should-remember-positions/294761) :busts_in_silhouette:"

Unfortunately, because they pop out undocked, your tool no longer works. To make matters worse, your implementation of touch support no longer works.

I (and many others) are very hopeful you may be able to update your tool to work around this and get touch working again.

Thanks in advance.

**Comment by rob2791** [comment]
Yes Please!! This is a great tool, and now Asobo has gone and screwed it up (again)!
Hopefully it's a simple fix!

**Comment by Crunchmeister1** [comment]
This new functional basically makes the popout management part of this tool obsolete now. But as a side effect, the touch support (the most important part IMHO) is now no longer an option.

**Comment by ourduck** [comment]
Just posted on the WT Discord and then thought to come here.  PopOut Manager has been a staple since AAU1 Beta.  I'm hoping for a fix here as I can't imagine flying with a mouse again!

**Comment by hawkeye-stan** [comment]
Hi all,

Thank you for the heads up. Looks like with breaking changes in how pop out works in SU12 beta, I will have to rework how POPM handles pop out panel and touch support in this new beta. I’m currently out of town but will be back home tomorrow night (Wednesday night) to install the beta and figure out the ins and outs of this new updates. Unfortunately I will also be out on a family trip this weekend but I’m hopeful that since I got this Thursday and Friday night before my trip, I will try to implement a new beta version of POPM that will work with SU12 beta. It will be publishing POPM update on github for you to download and test. Worst case scenario is I should have an updated version of POPM by early next week. All all users who are on official non beta release, POPM changes will not be a mandatory update and you will not see an auto-update notification.

Stanley

**Comment by Crunchmeister1** [comment]
Much appreciated, good sir. Your wonderful tool has been a godsend to many of us. I really hope you can get this sorted.

**Comment by hawkeye-stan** [comment]
Please see flightsimulator.com SU12 beta thread for updated information regarding SU12 compatibility.

https://forums.flightsimulator.com/t/popout-manager-not-working-with-beta/576906/10

**Comment by Ulazygit** [comment]
> Good evening,
> 
> MSFS SU12 just launched and with it, they have implemented a feature to remember where the screens have been placed after pop out and their size.
> 
> "Glass cockpit externalization has been reworked. There’s no intermediate window anymore; each glass cockpit opens a distinct window with the glass cockpit name. [Window position and size is saved when ending a flight. 9](https://forums.flightsimulator.com/t/popped-out-panels-should-remember-positions/294761) 👥"
> 
> Unfortunately, because they pop out undocked, your tool no longer works. To make matters worse, your implementation of touch support no longer works.
> 
> I (and many others) are very hopeful you may be able to update your tool to work around this and get touch working again.
> 
> Thanks in advance.

but can these popouts be made borderless like this?

![distoriton](https://user-images.githubusercontent.com/60723284/225988047-6d580e78-7ffd-490a-ba01-2aed6c3bad50.JPG)

**Comment by ourduck** [comment]
The pop outs for the Garmin GTCs are coming out borderless for me. I haven’t used it on an airliner.
