### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by SquidehOG** [hawkeye-stan/msfs-popout-panel-manager#70]
Hi, I had some issues with this albe it a great idea and wish to roll it back to a vanilla state.
It seems though its broken the native pop out screens and they no longer join together and now spawn offscreen.
Its also causes CTD's when a popout window wigs out ...any advice please to restore defaults?

Many thanks

**Comment by hawkeye-stan** [comment]
You can just delete the exe to remove POPM. As for issues you're seeing, the pop out screens not joining together, crashes and pop out spawn offscreen are issues created by SU12. 

1. For pop out not joining together, SU12 changed how pop outs are implemented so there is nothing you can do to get merged pop outs back. 

2. As for pop out spawing offscreen, it is a bug for SU12 that once MSFS remembers the state and location of pop out, it just gets stuck. I'm not sure how to clear the stuck cached info by MSFS. I'll investigate more into it and see if I can find a way to clear the MSFS saved state and location and will let you know. Please ask around in flightsimulator forum and see if there is a way to do this. Also, reinstalling MSFS may not help since the pop out locations maybe save to the cloud that is tied to the game.

Stanley

**Comment by SquidehOG** [comment]
Well with much reluctance I deleted cloud/local saves, reinstalled the sim and I can now confirm the sim docking windows are still broken! Where else is this mod leaving data please?

**Comment by hawkeye-stan** [comment]
If you’re not using POPM (not running and the game is running) and the pop outs are still broken, the broken pop out windows are still control by MSFS and not POPM. My app does not write any data that MSFS can read and use. 

Reinstalling MSFS won’t help since the game is associated with your online account, either Steam or Microsoft. Unless you buy another copy of the game or register the game with another user ID, your cloud data may still be there. You can open a support ticket with Microsoft and see if they can help resolve your issue.
