### ISSUE TITLE
Can't reliably popout two windows with "Hide Title Bar"

### ISSUE THREAD

**Issue by brianavid** [hawkeye-stan/msfs-popout-panel-manager#72]
If I popout two windows (e.g. G1000 PDF and MFD) and select "Hide Title Bar" for both, then when the automatic popout happens, the sequence appears to be:
1) Position panel 1 with title bar
2) Hide panel 1 title bar, which moves that panel into its correct final position
3) Position panel 2 with title bar
4) Hide panel 2 title bar, which moves that panel into its correct final position BUT ALSO moves panel 1 again - this time into the wrong position, presumably offset by the amount of movement needed for the title bar.

As I am using Air Manager, I can put that always on top, and so cover the panel title bars. I do not need to use POPM's Hide Title Bar. This is an adequate work-around, but the bug is still there.

**Comment by hawkeye-stan** [comment]
What you're seeing is an existing bug in MSFS since many service update (SU) ago. When POPM hides the title bar of one panel, this changes the size of this particular pop out. When this happens, MSFS somehow also moves or changes the location and/or size of other pop out window when it detects pop out size changes. This bug may not appear 100% of the time and I haven't figured out how to override this MSFS issue unfortunately.

Stanley

**Comment by brianavid** [comment]
Thanks for the response. As I said, I have an adequate work-around. It must be a real pain keeping a tool like this going on top of a shifting (and buggy) platform. So thanks for all your efforts!
