### ISSUE TITLE
MSFS config file for popout position

### ISSUE THREAD

**Issue by alanbeasy** [hawkeye-stan/msfs-popout-panel-manager#73]
Hi Stanley,
Can you tell me where to find the new MSFS 2020 POPout config file?

The reason I need it is because I have a multi-screen set up and I have just swapped my main Windows 11 screen to a different screen.
This has resulted in your POPOUT manager looking for the popouts in the wrong location.  
I fixed that within your program by editing the pop locations as well as unlocking/repositioning the popouts in Airmanager
I had to re-do that for all my different planes.
BUT……
There was a tricky problem I had to overcome.
The fact that MSFS "remembers" the location of the popout, when the popout was started, most of the popouts were "hidden" off screen because they were below the new main WINDOWS 11 screen - (where MSFS Flight SIM 2020 "thought" the AIR Manager window should be).
I had to "guess" by placing a minus "-" in front of the X-Pos.  
This brought the popped out window onto an AIR Manager screen so that I could then move it manually  into its correct location.

However, I would like to change the position that MSFS "remembers" because they are still off screen until your POM puts them on the required window.
That is not an ideal situation.
There must be a config file in MSFS with the X-Pos and Y-Pos that the SIM remembers.
If I can adjust the positions there, they will be closer to where they are supposed to be before your POM does its final adjustment.

thanks

**Comment by hawkeye-stan** [comment]
Hi Alanbeasy,

Unfortunately, the pop out locations that MSFS remembers are saved in the cloud. If there are backup local copies (in case the cloud version got corrupted), they should be in the following folder but the files look like are all in binaries which cannot be edited:

C:\Users\YOURUSERNAME\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\SystemAppData\wgs (MS Store)
C:\Users\YOURUSERNAME\AppData\Roaming\Microsoft Flight Simulator\Packages\SystemAppData\wgs  (Steam)

This issue is causing some pop out users problem because if they have flown an aircraft, even from months ago and then update their monitor setup after that. After update the game to SU12, pop out location for these aircrafts have become active (Asobo probably was reading this information from previously sotred information and just implement the recall part of the new feature in SU12), pop out is now off screen and no way to get them back. One user fixed this issue by deleting all his cloud data (which includes game settings, logged flight hours, etc).

Anyway, if you've encountered this issue with off screen pop out in the future, you can use POPM to perform a work around. Just follow the below steps.

  1.  Use an existing or create a new profile in POPM
  2.  Perform the usual select which instrumentation panels to pop out
  3.  Let POPM try to pop them out, they'll be off screen and it will look like POPM didn't do anything
  4.  If everything is successful and no error in POPM, in POPM panel configuration screen, you'll see panels with off screen coordinates, just change them to X: 0, Y: 0, this will put the pop outs at the upper left corner of your main monitor
  5.  Now, important! Go back to the game and exit the flight without closing the pop outs, this will force MSFS to re-save the pop out location
  6.  During subsequent flight, MSFS will automatically pop out these panels at the saved locations if you either do it manually (Right-Alt click) or using POPM. You can always use POPM to override these locations to your liking.

Hopefully, Asobo will fix this issue in SU13.

Stanley
________________________________

**Comment by hawkeye-stan** [comment]
Keeping this topic alive for other users to fix disappearing pop out (off screen pop out).

**Comment by hawkeye-stan** [comment]
In version 4.0, please go to Help => Support section and there is a link you can click to open the POPM configuration files location.
