### ISSUE TITLE
Crash after finish flight

### ISSUE THREAD

**Issue by brian630** [hawkeye-stan/msfs-popout-panel-manager#75]
Hello, I am facing a problem after I finish a flight. Click "Main Menu" in the pause menu. After loading around half of the progress bar it crash the whole MSFS. I already test that only when I am using popout panel manager will have this issue. Thank you.

**Comment by hawkeye-stan** [comment]
There could be the game has something in conflict with SimConnect (POPM uses it) or SimConnect is crashing the game. That's the only interaction point where POPM connects to the game. SimConnect is widely used by plugin developers and it does have issue from time to time with the game. I haven't received reports of POPM crashing the game recently and unfortunately I'm not able to reproduce your issue. My recommendation is not use POPM to manage pop outs and instead use the built-in save/load pop out management feature of MSFS since SU12 because your POPM issue is most likely system specific. 

Stanley

**Comment by brian630** [comment]
Hello, I found a solution that works perfectly. First use POPM to pop out all the windows. And then Close the POPM windows. After that it will not crash when I go back to Main Menu.
