### ISSUE TITLE
On 2nd pop out of panel, black bars at sides - ratio changes

### ISSUE THREAD

**Issue by Rosen213** [hawkeye-stan/msfs-popout-panel-manager#76]
As title above, but on first setting up the pop out, then alt+enter to make fit screen, all is good.  On loading the aircraft for 2nd time, screen auto pops out but ratio is incorrect and black bars both sides of panel, not filling screen.

Only way I have found to fix this, is to restart and redo panel selection from beginning again.

**Comment by hawkeye-stan** [comment]
Panel ratio is control by MSFS and there seems to be a consensus that one of the SU broke the scaling (on first load or subsequent load). And SU12 most likely made it worst by adding partial feature to save/load pop out size and location and full screen scaling probably got mess up too. When you redo panel selection, POPM is always popping out panel "after" SU12 auto load panel size that's probably why it works. And after that, POPM is unable to override what MSFS SU12 is doing because of timing issue since POPM has no way to determine when SU12 applies the auto load panel size settings. If you need full screen pop out, you may not be able to use POPM auto pop out until I figure out how to reliably override SU12 saved pop out panel feature.

https://forums.flightsimulator.com/t/msfs-pop-out-panel-manager-with-touch-support-v3-4-6/460613/721
