### ISSUE TITLE
vPilot incompatibility 

### ISSUE THREAD

**Issue by ModdeOnAir** [hawkeye-stan/msfs-popout-panel-manager#78]
I´m running into some issues with the vPilot client as soon as I start the popout panel manager and panel popout process. If the game is freshly started everything works fine, I can tune into the radio frequencies and listen/talk. As soon as I start the manager, the whole radio system seems to be broken and I can no longer interact with the radio in vPilot. I´ve tried to remove all panels and close the manager, but the only thing that gets vPilot back to normal is a full sim restart.

**Comment by hawkeye-stan** [comment]
Please make sure you do not check the checkbox "Power on required to pop out panels on cold start (G1000/G3000). This will turn on then off power and avionics to work around a long standing MSFS bug that G1000 panels cannot be popped out when power/avionics is off. I'm guessing your issue is if avionics is off, radio will not work.

Other than that, I'm not sure anything else in POPM that interacts with radio system for your aircraft.

Stanley
