### ISSUE TITLE
4K issue

### ISSUE THREAD

**Issue by comcon-1** [hawkeye-stan/msfs-popout-panel-manager#8]
Hello Stanley,
when using 4k (4096x2160) on main display with two full HD displays, pop out does not work correctly. The windows are too big. Please see screenshots. Even if I touch a field like X POS, the corresponding panel doubles the size.

I use V 3.1 (software says 3.0)

Best regards
Olive
![setup](https://user-images.githubusercontent.com/96527935/151629017-b36cae1d-1a3f-4639-8518-b693fa1ba549.png)
![Saved pop out](https://user-images.githubusercontent.com/96527935/151629075-46a5bd36-e73a-49e8-bbc8-04a83e005502.png)
![Using profile](https://user-images.githubusercontent.com/96527935/151629172-61eccc87-8b77-4272-abe1-8b2144d16ecf.png)
![After touching X POS](https://user-images.githubusercontent.com/96527935/151629289-e349fc9f-d6b0-4a58-849e-cafc21983413.png)
r

**Comment by hawkeye-stan** [comment]
Hi Olive,

I've create a custom hotfix release and hopefully it will fix your problem. Please download the release package "msfs-popout-panel-manager-dpi-hotfix.zip" from the version 3.1 release section. Just unzip and overwrite your existing files. Btw, the version you're using is still v3.0. Version 3.1 has brand new menu system.

For testing the hotfix, unfortunately, I currently don't have a 4K high DPI monitor to thoroughly test this hotfix (sadly my 4K monitor broke the past weekend), but I was able to reproduce your issue by using my 1440p monitor and create a 4K out of band resolution. I was able to recreate the messed up window rendering. I believe the issue occurs when using a 4K monitor with windows scaling of > 100% in conjunction with one or more lower resolution monitors. Please report back and I hope the hotfix release fixes your issue. If so, I'll incorporate the code in my next official release. 

Thank you for taking the time to report the problem and create screenshots, it really helps me identify the problem!

Stanley

**Comment by comcon-1** [comment]
Hi Stanley,
thanks for your work. The Panels selection works, but sometimes the numbers at the instruments are not shown. Nevertheless the selected panels appear in your App. When starting to pop out, the error occours: Unable to pop out the first panel...

I also tried to change the size of the msfs window without any success.

Best regards
Oliver

![Screenshot 1](https://user-images.githubusercontent.com/96527935/151665913-e3da87aa-38d9-4dbe-814f-798f3c81c12c.jpg)
![Screenshot 2](https://user-images.githubusercontent.com/96527935/151665918-9f38665d-f925-4136-b3d3-d9db04539931.jpg)

**Comment by hawkeye-stan** [comment]
The two panels coordinates do not seem to be right for a 4k 100% scale screen. With Y position of 1040 out of vertical resolution 2160px, my app is detecting the PFD and MFD are in the middle of the game screen instead close the bottom of the screen. The X pos are off too.

Will you be able to help me double check couple configurations?

1. You are running the game in window mode instead of full screen.
2. What is your windows OS scaling in display settings for your 4K screen. I am guessing it is around 175% or 200%.

I think with the game in window mode (or possibly full screen mode) with high DPI monitor and non 100% windows scaling, it is translating mouse click coordinates between Windows OS and the game incorrectly. I will do investigating on my end and see how the coordinates behave.

**Comment by comcon-1** [comment]
Hi Stanley,

1: Same with fullscreen mode. Sometimes pop out works until the two panels
are in one window.

2: Your guessing was correct, I was on 200%

I changed to 100% and the app worked immediately.  So scaling of the
desktop is the problem.

Best regards
Oliver



Stanley ***@***.***> schrieb am Sa. 29. Jan. 2022 um 19:58:

**Comment by hawkeye-stan** [comment]
Glad that the temporary workaround of changing windows OS desktop scaling to 100% worked for you. 

But that's an inconvenience for you to do that every time you've to play MSFS. I'm keeping this issue open and making it a top priority to find a permanent fix in the next release. And your reported problem may be related to issue #5 that another user reported previously.

Please keep an eye out for the next release and hopefully it will make your experience of using this app much smoother and once again thank you for reporting the problem to help make this app better!

Stanley

**Comment by comcon-1** [comment]
I appreciate your work, thanks. If you want me to try things out, let me know. I´d be glad if I can help.

Oliver

**Comment by hawkeye-stan** [comment]
Please try out Version 3.2 beta and report back if it fixes your issue.

**Comment by comcon-1** [comment]
Sure, it is a pleasure to test this out.
I tried 125%, 150% and 200% scaling and all worked perfect. Thumbs up!
I like the Power on required feature, as I usually start with cold and dark, but it only works for the PFD. If it is possible, add this feature to the MFD as well.

Best regards

**Comment by hawkeye-stan** [comment]
The power on for cold start should work for both PFD and MFD for the G1000 (Actually I tested with Working title G1000 nxi). Are you getting any error messages on your end when auto popping out panels? If you are using the default original G1000, maybe it is not accepting the Simconnect command I coded? For PFD, it is turning on battery master and for MFD, it is turning on avionics master. Please see the video I created for this feature using g1000nxi. Please let me know which version of g1000 you are using and I will do more testing in my end. And so far, I only find g1000 cannot be popped out on cold and I think it is a bug in the sim.

**Comment by comcon-1** [comment]
I also use the NXI. When in cold and dark only the PFD is poping out. When I switch on Avionics on my Alpha (with master off) both are popping out. Maybe it is refusing because I have a hardware switch.
By the way: Autostart and Auto Pop Out is not working on my end.

**Comment by comcon-1** [comment]
Just saw that there was an error message after closing the sim. Here is the error log

[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/8011336/error.log)
.

**Comment by hawkeye-stan** [comment]
Thanks for the attaching the error.p log. I will investigate what is causing your issue and will get back to you with a fix.

**Comment by comcon-1** [comment]
Hi Stanley,
I´ve binded the profile to the 172 and turned on Auto Start. I just want to let you know, that the feature (pressing Ready to fly) only works in Windoed Mode. In Fullscreen Mode the button will not be pressed, resulting in not popping out of course.

Best regards
Oliver

**Comment by hawkeye-stan** [comment]
Hi Oliver,

Got few minutes between my office meetings. Want to update you on MFD not popping out on cold start with honeycomb alpha hardware button assigned. Did a little research on the alpha, and probably applies to other flight controls with hardware assign button in general. You're correct on the possible cause for the issue. It continuously sends a SimConnect signal to the game regarding its button state so it will not get out of sync with the game. So if the alpha avionics switch is off, it continuously sends a "turn off" signal every X milliseconds. So even my code sends a "turn on" signal, alpha will overwrite the button state almost immediately and turn the panel off. I try looking into a hack to get around it or anything I can do with a custom WASM module but it probably won't work, the game is not even sending a panel "is now available" signal so I can Right-Alt click the panel when it is dark. I believe it is definitely a bug on the G1000 panels and hopefully Asobo will fix this issue on SU8. All the other planes I've tested do not exhibit this behavior. I'll continue the research and see if there is a workaround because I don't believe Asobo has this bug as top priority on their fix list. And on a personal note, I want this to work too since I'll probably upgrade my thrustmaster flight stick to the alpha/bravo combo  in the near feature.

I'll open another ticket regarding the auto start panel feature not clicking the "ready to fly" button in full screen mode on 4K monitor. Please add a bookmark to that. Unfortunately, I won't have time to research on it in next couple days but will get right on it after I get back from work trip later this week.

Once again thank you for helping me beta test this software, your input is invaluable!
