### ISSUE TITLE
Not returning focus to Sim after using touch

### ISSUE THREAD

**Issue by leinhto** [hawkeye-stan/msfs-popout-panel-manager#81]
I am using direct USB connection with Space Team. I thought it was Air Manager but even with Air Manager turned off it still does not return focus after touch.

Also, i need to click twice to get touch working. One to get a mouse pointer to the item I click and then once more to actually touch the item. It is almost as if it is micmicking moving the mouse.

**Comment by hawkeye-stan** [comment]
I've just tested with SpaceDesk and unable to reproduce your issue. Please try version 4.0 of the application and see if you need to click twice to get touch working. The automatic refocus should be activated when you touch the pop out.

**Comment by leinhto** [comment]
I figured out it was whenever one of the tablets got disconnected. For some reason the PC gets confused and doesn't know which should be Always on top AirManager or Pop-Out Manager. Then the return to sim stops working unless you shut both down and restart them.

I got 4.0 though nice. Got a new issue though. It won't pop-out the FMC window now.

**Comment by hawkeye-stan** [comment]
FMC window for which aircraft? Can you manually pop out this FMC window using Right-Alt click? If you define the location of panel correctly, POPM should be able to pop the FMC window up.

In Air Manager, try to set "click passthrough" then if Air Manager becomes always on top window or both app get confuses after tablet disconnect, Air Manager will pass the click through to the pop out window underneath and POPM refocus will work.

**Comment by leinhto** [comment]
It is for the CJ4. Yeah, I can pop it out manually. But I can't interact with it via Pop Out Manager.

Also, the Click-Trough option is grayed out for me in Air Manager so I still get times when the pop outs don't stay always on top and I have to click the simulator to bring it to the top.

What do I need to do to get the Clock -Trough working?

**Comment by hawkeye-stan** [comment]
I just did a quick test and I think the CJ4 is currently very buggy in MSFS. I'm encountering many issues trying to manually pop out panels:
- Sometimes RALT-Click to pop out panel does not work
- Sometimes can only pop out with RALT-double click (this is happening a lot and maybe only for this particular aircraft?)
- Sometimes can only pop out 2 out of 3 panels manually 
- The FMC mouse focus is bugged, it needs 2 clicks to focus before manual pop out can occur.

Another thing I notice for CJ4 FMC, if you hover the mouse over PFD and MFD, it is an arrow icon (which I believe is correct since these panels are displayed only). But for FMC, it changes to a hand icon which is not correct since FMC is also a read-only panel (MSFS bug).

Lastly, I've updated my code to force a double click in POPM to execute pop out. Now FMC works but than MFD does not work.   And then manual pop out locks up and does not work at all. Need to restart the flight to fix it. Yikes!

I've do more testing to see what is going on with this aircraft. Maybe I've a plugin that is conflicting with it. If CJ4 requires inconsistent clicks, then I won't be able to code workaround in POPM to overcome this issue.

As for Air Manager click passthrough, I'm not sure why your option is grayed out. Would you be able to contact Air Manager support to see if they can help? And since Always on Top is not reliable in Windows OS for any applications, you most likely will encounter windows will overwrite each other Always on top settings. 

Stanley

**Comment by leinhto** [comment]
Gotcha. Thanks for the quick check. I will check with AM support on the Click-Through.

Thanks for your support.

**Comment by ToddLorey** [comment]
> 

You have to disable or "hide" the Air Manager panel to allow changes to the click through.  Just click the light bulb to dark in the Air Manager Home tab.  I'm guessing this is the fix you're looking for.

**Comment by leinhto** [comment]
Yep. That did it. I got that insight too from the Air Manager forum. Thanks.

**Comment by hawkeye-stan** [comment]
Quick update for not able to pop out CJ4 FMC panels, I've run tests by disabling all community plugins and deactivated all external apps that I used that interact with MSFS (ie. FSUIPC, little nav map, simbrief). Unfortunately, the double click required issue is still happening. I've to dive deeper into any MSFS code that I've access to and see if I can find the root cause.

**Comment by hawkeye-stan** [comment]
Please try version 4.0.1.3 pre-release and see if this beta release works for you to pop out all panels on CJ4.

**Comment by leinhto** [comment]
Works now.
