### ISSUE TITLE
Unable to select windows while in setting up for B787

### ISSUE THREAD

**Issue by Jacktherookie** [hawkeye-stan/msfs-popout-panel-manager#85]
I've recently found out that cannot select B787's PFD due to recentering view while selecting windows for pop out.
I'm currently using 32 inch QHD monitor and I just can't.... Any help?

**Comment by hawkeye-stan** [comment]
When you first create the profile, you should be able to move the camera view, or zoom in/out to select the PFD. After that, it uses custom view keystroke Ctrl-Alt-0 (save) and Alt-0 (load) to reset the camera view for your selection. To overcome an existing MSFS bug, POPM needs to recenter the view first before executing the custom camera view. Maybe either your custom view control binding in MSFS is not set or working correctly or 787 has new camera issue since the latest MSFS update. 

Would you double check you've everything set correctly and I'll try to replicate your issue on my end to see what could be the cause of your issue?

Stanley

**Comment by hawkeye-stan** [comment]
Just did I test, looks like the default 787 behavior is the game zoom in on the cockpit view and make PFD not visible. What you need to do is the use the mouse view to zoom out first so the panels are all visible when defining the panels to be popped out. Also make sure your zoom setting in MSFS general options - camera is set to 50%. There is currently a bug that if the zoom setting is anything other than 50%, saving and loading of custom camera view (which POPM relies on) does not work correctly.

![screenshot](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/685a74f0-6d9d-45f0-84a7-0b6c8a6953af)


Stanley
