### ISSUE TITLE
Problem popping out the FMC screen of the CJ4

### ISSUE THREAD

**Issue by JaimeLeon2** [hawkeye-stan/msfs-popout-panel-manager#88]
I upgraded popout panel manager and now I find I cannot correctly popout the FMC screen in the default CJ4. I had the FMC screen last in the sequence and it failed every time. I moved it as first in sequence and it popped out, but all the other screens failed. I see something flashing at the bottom of this display while the popout is happening. Maybe keyboard input being activated? 

It had been working well before the UI was reworked. I didn't use it for a couple of months and now this happened.

**Comment by hawkeye-stan** [comment]
Please download v4.0.2 from github. It has a workaround fix for CJ4.

**Comment by JaimeLeon2** [comment]
Thank you for the prompt response.  I will try it.

**Comment by hawkeye-stan** [comment]
Cool. Let me know if the new version fixes your CJ4 FMC issue. If so, I can start rolling out this version to all users who may have experienced your issue. Thanks!

**Comment by JaimeLeon2** [comment]
Beta v4.02 worked very well now popping the CJ4 FMC screen.  Thank you.
One question, for the FMC screen I usually have to resize it with popout panel manager with window borders in my FMC hardware unit screen and then manually press Alt-Enter for the popout to fill the screen (stretching the text to fill the screen).  Is there a way for popout panel manager to do that automatically?  The full screen option does not appear to do anything.
Thanks again for a great addon.

**Comment by hawkeye-stan** [comment]
POPM should be able to pop out FMC screen, place it on your FMC hardware unit screen and expand to full screen automatically. What you need to do is to configure the panel to have the correct aspect ratio you wanted when it is a pop out window before selecting the full screen mode option. See the screenshots below as I'm using my 1080p monitor as example:

1. Move the FMC pop out to your FMC hardware screen and then resize it to have your desire aspect ratio. In the following screenshot, it has left and right black border.

<img width="361" alt="screenshot1" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/ab5ca965-b314-4a02-96e8-220934201fc1">


2. Now in POPM, activate the "Full screen mode" for this panel. Your panel should now expand to fill the entire screen with the same aspect ratio. Screenshot below is for my entire monitor screen.

<img width="960" alt="screenshot2" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/3917a094-96c0-4330-9005-8196abaef293">

3. Here is the config for the FMC panel. Also, once you've it configured, lock the profile since an existing MSFS panel sizing bug may change the panel size and location when you about the exit the flight and update POPM panel information.

<img width="745" alt="screenshot3" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/9c3e26ee-2ff0-4e57-a8ad-05bf7032399b">

When you start pop out next time, the FMC panel should pop out, move to your FMC hardware screen as a pop out window using your defined panel size, and then expand it to full screen.

**Comment by hawkeye-stan** [comment]
I've updated POPM v4.0.2 beta for a potential fix to the full screen mode issue. Please download the latest v4.0.2 beta if you would like to try out the fix. Unfortunately, I'm not able to verify it since I'm not able to reproduce this particular issue but another user PM me and had similar issue to yours and hopefully this fix will resolve it. The user description of the issue is that the pop out is not focused when POPM trying to apply full screen mode to it.

[https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/tag/v4.0.2](https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/tag/v4.0.2)
