### ISSUE TITLE
Failure to load custom camera views.

### ISSUE THREAD

**Issue by Thick8** [hawkeye-stan/msfs-popout-panel-manager#94]
The program fails during "Loading custom camera view". I've tried several different panels in several default aircraft. SimConnect is running. I've turned off all additional add-on. Just the base game and Pop Out Manager running. Emptied the community folder. I'm stumped. Where would be the best place to go for troubleshooting help?
Thanks,
John

**Comment by hawkeye-stan** [comment]
"Loading custom camera view" failed is because for the aircraft that you're trying to have panels pop out, the custom camera view used by POPM to define the colored circles location does not exist. The default keystroke for custom camera view for POPM to save the colored circles is Ctrl-Alt-0/Alt-0. So before you try to use a POPM aircraft profile in an aircraft, please click the source panel icon below.

<img width="745" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/8d179395-1edf-46b2-8053-ecb9ba0268d5">

If you do not have a camera view defined, the screen may not move at all. In any case, once any camera movements settle down, make sure the colored circles line up with panels you want pop out. Then click the source panel icon again. POPM will then save the current view to custom camera view by using the default keystroke of Ctrl-Alt-0. You can test is everything saved correctly by moving to a different view/cockpit angle using your mouse and pressing Alt-0 on your keyboard. 

If you get the "Loading custom camera view" failure at the end of the pop out process. Please make sure you also have a custom camera view define or just use the default "center camera view" setting. In the screenshot below, I've Alt-9 to move to a view that I defined after pop out is completed.

<img width="762" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/54ab30a1-6b07-4f09-8727-0b8bcf2be506">

**Comment by hawkeye-stan** [comment]
After camera error message is fixed in v4.0.3
