### ISSUE TITLE
Some panels won't pop out

### ISSUE THREAD

**Issue by mirosme** [hawkeye-stan/msfs-popout-panel-manager#95]
Hi there,
This is a great software, but it is unfortunately not usable unless it helps with the issue that some panels won't pop out. I don't know if these are off-screen or what, simply nothing happens and the automation fails for those panels while others work no problem.
Thanks,
Miro

**Comment by hawkeye-stan** [comment]
If you're not able to pop out panels in POPM, it could be misconfigured POPM profile or issue with the aircraft itself. If you've configured panels correctly by creating a new aircraft profile in POPM (colored circles lined up with panels you want) and getting error during, then either the panels are not designed to be popped from the aircraft or something is off. If you're not getting error but the panels are not on screen, most likely they're offscreen (MSFS issue). 

Try popping each panel you want manually to see what types they're. In MSFS, most glass screen based panels can be popped out but dials are not.

**Comment by DrDave-4021** [comment]
I'm having the same problem. Where should the circles be located? How can we find out what app is blocking a popout?

I have an MSFS test bed. I am trying to pop out G1000 PFD & MFD from a third party Mustang C510. Both work fine with MSFS popout (Rt alt / rt mouse).

The only way I get it to work is to a delete cloud saves and reinstall popup manager. Do you know of anyway to reset the popout windows location to the msfs home window without deleting the cloud saves? The delete cloud saves also deletes controls, general options, accessibility, assistance, etc. A total pain just to find the popout screens.

If one deletes a popup line item and color, can you also delete the same window? Could you have a facility to delete any popouts for an aircraft if a new profile is created for a previous profile of the same aircraft?

Could you provide more details of the "Start Popout" window entries?

Also, could you provide indents on your .json modules in the documents\msfs popup manager folder?

Thanks

**Comment by mirosme** [comment]
Same as @DrDave-4021 I meant the displays that should and would pop out at some point, but simply won't now. I also went through the hassle of deleting cloud saves and it helped before, but the issue came back again. In the meantime I configured everything to my liking, so deleting my saves every time this happens is not an option.

I was hoping your tool could somehow locate the windows (if off-screen) and close them or whatever.

**Comment by hawkeye-stan** [comment]
Hi Mirosme and DrDave-4021, you don't have to delete cloud saves since it will also remove all your flight control bindings, flight logs, general options settings, etc.

The disappearance of pop out windows is an existing MSFS bug/implementation that a lot of users have been complaining. If pop out's coordinates were saved to off screen location by MSFS, either intentionally or accidentally, there is no way to get the pop out back without either deleting cloud saves or by using POPM as workaround.

Here is the step by step instructions and what you would see when configuring G1000 PFD/MFD (use as example) and what happens if pop out were off screen and how to fix it.

1. Add a new profile in POPM, this will make sure the custom camera angle is being saved by POPM.
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/72913e92-202b-4768-834d-0505eba79129)

2. Now click the toggle edit panel source icon, this will save the current camera angle for the colored circles which are over the panels you want to pop out.
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/ffe15ac4-e683-445c-8612-08c2b8df809a)

3. Also, notice the initial coordinates for these panels are all zeroes. POPM does not know about these panels yet until after the first pop out.
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/ed8b75ee-57c3-433e-a37a-f62ab0ccb92e)

4. Click "Start pop out" button, if everything works correctly without error in the pop out progress messages dialog (Right-Alt, Left-Click) is also working, you should see pop out panel comes on screen and at the upper left corner of your monitor. Also, notice the default coordinates. They started at top:0/left:0 for first panel and the next one has 30 pixels offset. Also notice a green border around each panel which means POPM is able to detect these panels.
<img width="1749" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/66a95adc-862a-44f0-945b-dc686bb251b0">

5. Here is situation when panels are off screen. POPM should still be able to pop out the panels, but they won't appear on screen. You can see that when panel configuration for each panel in POPM still has a green border around it, this means POPM is able to detect the panel but it could be off screen. Second, the coordinates for each panel will be off (could be some negatives numbers or some big numbers that is outside your monitor defined coordinates).
<img width="1771" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/b460b3b8-3b6e-416c-ad0a-45196d5d1689">

6. To get the panels back into view, type 0 to the top and left coordinate for the panel. This will move panel back to the upper left corner in your main monitor. 

7. Once you get panel into view, just do your panel configuration and move them into your desire location.

8. *** IMPORTANT ***, now click the lock icon and LOCK the profile to prevent any accidental changes by you or MSFS. The lock icon should turn green.
<img width="748" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/5f524154-c897-4ada-bc00-0a3d970b98ce">

9. If you exit the flight now, the current panel location should be saved by MSFS and if you try to manually pop them out again, the panel should be at the defined location (this is how MSFS cloud saves works). But the coordinates could get corrupt again by MSFS and disappear again.

10. Since you already have POPM profile configured, you can start pop out again, panels will go off screen, POPM will then override it and move the panels back into view.

11. Lastly and a quick tip, if you want to play with the panels coordinates but you don't want to unlock the profile and make accidental changes, you can make a copy of aircraft profile. But make sure you don't change the custom camera angle when defining color circles since POPM can only manage a single custom camera angle that applies to the original and copied profile.
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/237ef983-1b40-4662-bed8-6d9f52a7ad01)


Stanley

**Comment by mirosme** [comment]
Awesome! The panel had a negative coordinates exactly as you've shown. Issue is now solved, thank you very much!

**Comment by hawkeye-stan** [comment]
Keeping this ticket for reference to resolve this common issue.
