### ISSUE TITLE
One source opening two pop outs

### ISSUE THREAD

**Issue by alanbeasy** [hawkeye-stan/msfs-popout-panel-manager#97]
Hi Stanley.  Love the Pop out manager.  Starting to get a bit more sophisticated, but adding some complexity and issues?  
I was having frustration with the KingAir350i.  After selecting the PDF and MDF pop outs, they would swap positions on the next pop out... and the PDF source would adopt the name of the MDF pop out etc.
I gave up and decided to just use one pilot PDF  pop out rather than fighting it.
What I found then was if I select just the pilot PDF window, the MDF pops out as well… so I positioned both of them at that time. 
So I now just have ONE pop out location configured and both pop outs go where they are supposed to.

I have tested MSFS using right ALT click  (without the Pop Out manager open) and only the selected window pops out - in the correct location.

I do not seem to be having any trouble with my other profiles, but they were all created before the latest update.
I won't know if the issue will the KingAir350i will occur in other planes until I set up a new plane

Cheers
Alan

**Comment by hawkeye-stan** [comment]
Sorry for the late reply. I've run some tests by setting up a new profile on King Air 350 and unfortunately, I'm not able to reproduce your issue.

The issue you encountered had been reported a year ago and I've experienced this issue myself on couple other aircrafts. When POPM tries to pop out panel too quickly, MSFS will pop out the wrong panel, swap panel, or the same panel twice. This also happened sometimes when I tried to manually popped out panel (on Flybywire A320) using keyboard. When this bug happened, restarting the game will usually fix the issue. But I guess this bug is somehow happening on your end consistently. 

For the past year, I haven't encountered this bug in the game and I am not able to reproduce it on-demand today either when I tried to get King Air to pop out the wrong panel.

**Comment by alanbeasy** [comment]
Thanks again,
Just a little update.  I have not flown anything for a week, so today I
fired up the computer and took the KingAir 350i for another spin.

POM popped and placed the pilot PDF...... and the middle MDF.
But I still only have the PDF “location” set in the Profile.

So I am ignoring it for now.
I use little Navmap on the RHS monitor so I just close the MDF.

I am guessing that whatever is the config file for POM to remember the
profile positions, it has somehow gotten messed up for the KingAir 350i.

I could try deleting the profile and restarting everything before
recreating the KingAir profile, but for now I am “letting sleeping dogs lie”

Cheers.
Alan

**Comment by hawkeye-stan** [comment]
Since POPM has only configuration for PFD, the MSFS bug was triggered which both panel popping out did occur when POPM is only trying to pop out PFD. Once both panels were popped out, PFD correctly by POPM and MFD because of the game bug, then POPM placed the PFD using its information, and MFD was placed  by MSFS remembering panel location with its cloud save. If you reinstall the game or delete MSFS cloud save, the MFD will not be placed correctly (please do not do that since you will lose many game information such as control settings, flight logs, etc) So the MFD is not placed by POPM and POPM does not have and recalled some existing history for MFD location.

Unfortunately, your whole issue is pretty hard to explain. You are seeing the effects of a half-bake Microsoft pop out management implementation. And the result makes it looks like POPM is doing something but it is not. As of now, I have not figured out a way to get around this MSFS bug. Maybe when SU 14 release or in future patch release, there is way for me to read exact pop out panel information.

Stanley

Stanley

**Comment by alanbeasy** [comment]
Thanks for the explanation.
