### ISSUE TITLE
Why can't the PFD be pop out after the PFD is rendered to the screen with panel.cfg 's parameter render_on_screen?

### ISSUE THREAD

**Issue by szsailing** [hawkeye-stan/msfs-popout-panel-manager#98]
Hello。
I use the parameter render_on_screen of panel.cfg to display the PFD on the screen where I specify it. Now I want to pop out it out, but it always fails. The interface prompt is shown in the following figure. How can this problem be solved?
![微信图片_20231114112117](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/6753483/8d917a82-de9f-459e-aa07-4da7abb1bdb7)

**Comment by hawkeye-stan** [comment]
Hi Jack,

I don't think you can pop out the panel once you modify it's rendering in panel.cfg. Since the panel no longer sits inside the instrumentation frame which response to keystroke even / CoherentGT event that MSFS uses to code the game, the panel probably cannot be popped out. I'm not 100% sure and don't have experience about your special use case.

You can ask around in flight sim forum to see if another other users is doing what you're try to perform.

Stanley
